BASE = data.c data.h
FLAGS = -Wall

all: greedy harmonic work

greedy: $(BASE) greedy.c
	gcc $(FLAGS) data.c greedy.c -o greedy

harmonic: $(BASE) harmonic.c
	gcc $(FLAGS) data.c harmonic.c -o harmonic

work: $(BASE) work.c
	gcc $(FLAGS) data.c work.c -o work
